### ISSUE TITLE
copySecrets is copying secrets too late

### ISSUE THREAD

**Issue by hnicke** [garden-io/garden#3111] opened 2022-08-18 08:24 UTC
### Current Behavior
When running `garden deploy`, the secrets configured via `copySecrets` directive are copied too late to the deployment namespace resulting in failed deployments.

### Expected behavior
The secrets configured via `copySecrets` directive are being copied before any services get deployed.

### Reproducible example
1. I've deleted the deployed environment (`garden delete environment`)
2. I've redeployed the environment (`garden deploy`)
3. kubernetes deployments are created before the configured secrets are created. This leads to pods failing with status `CreateContainerConfigError: secret 'foo' not found`
4. eventually (after about 30 seconds) the secrets configured via `copySecrets` directive are being created
5. eventually the deployment controller restarts the failed pods and the deployment recovers - however, the `garden deploy` command exits with code 1: `2 deploy action(s) failed!`

### Suggested solution(s)
As a workaround I've written an exec service which fetches the relevant secrets via kubectl, strips metadata and reapplies them to the deployment namespace.

### Your environment

* **OS:** arch linux
* **How I'm running Kubernetes:** GKE

`garden version`
0.12.44

**Comment by Orzelius** [comment] 2022-08-18 08:28
This will most likely be fixed with the next major release where we rework the entire stack graph and garden internal task resolution to fix issues just like this. The release (`0.13`) is aimed for September.

**Comment by hnicke** [comment] 2023-01-08 10:21
Still relevant. Maybe the upcoming v0.13 release will fix it.

**Comment by vvagaytsev** [comment] 2023-10-27 15:24
This might be related to #3894.

**Comment by 10ko** [comment] 2024-01-31 10:55
Closing this since it should be fixed now. Please re-open if the problem is still persisting.

**Closed by 10ko** 2024-01-31 10:55 UTC
Labels: reexamine-post-0.13
