### ISSUE TITLE
Pulumi stackReference output empty

### ISSUE THREAD

**Issue by fabianboerner** [garden-io/garden#4425] opened 2023-05-23 23:21 UTC
### Current Behavior

stackReference not working if no new version deployed, it shows following error

"Invalid template string (${actions.deploy.upstash-kafka.out…): Could not find key clusterId under actions.deploy.upstash-kafka.outputs. Available keys: (none)."

only when garden discovers a new version the outputs are available

### Expected behavior

outputs should be available when having no changes in the deployment 

### Reproducible example

```kind: Deploy
type: pulumi
name: upstash-kafka
description: Creates upstash kafka instance
spec:
  createStack: true
  cacheStatus: true
  stack: "${var.customerId}-${environment.name}"
  pulumiVariables:
    app-infrastructure:stackName: "${var.customerId}-${environment.name}"
    app-infrastructure:customerId: ${var.customerId}
    app-infrastructure:orgName: ${var.pulumiAppOrg}
```

```kind: Deploy
type: pulumi
name: upstash-kafka-credential
description: Creates upstash kafka instance
dependencies:
  - deploy.upstash-kafka
spec:
  createStack: true
  cacheStatus: true
  stackReferences:
    - ${actions.deploy.upstash-kafka.outputs.clusterId}
  stack: "${var.customerId}-${environment.name}"
  pulumiVariables:
    app-infrastructure:stackName: "${var.customerId}-${environment.name}"
    app-infrastructure:customerId: ${var.customerId}
    app-infrastructure:orgName: ${var.pulumiAppOrg}

 ```

### Workaround

no workaround found

### Your environment

* **OS:** Ubuntu 22.04

`garden version` 0.13.0

**Comment by fabianboerner** [comment] 2023-05-23 23:40
If you have multiple garden files with the same stack name it deletes the one first created also.

**Comment by Orzelius** [comment] 2023-05-25 09:36
@fabianboerner thanks for bringing this to our attention, we'll look into it asap ❤️

**Comment by Walther** [comment] 2023-05-31 08:21
Thank you for reporting this issue!

Unfortunately I have been unable to reproduce this issue so far. We have an [example pulumi project](https://github.com/garden-io/garden/tree/main/examples/pulumi) which also uses an output in a `stackReference`, and it deploys correctly using `garden deploy`. Even after the first deployment, without making any changes to the configurations, both `garden validate` and `garden deploy` pass successfully - I don't see any errors about missing outputs.
https://github.com/garden-io/garden/blob/4dc6735b5bffe2a007cb0573bd487e593ab96b3e/examples/pulumi/k8s-deployment/garden.yml#L9-L15

Would it be possible for you to create a fully reproducible example, for example as a git repository, with all the needed configuration for the error to show up? You could base it either on our pulumi example or your own project, whichever is easier.

> If you have multiple garden files with the same stack name it deletes the one first created also.

I also wonder if this could be a useful thread to pull on - is there any chance your original issue was caused by conflicting stack names? We do have validation for conflicting action names, but not for the `spec.stack` field of pulumi actions.

**Comment by fabianboerner** [comment] 2023-06-05 23:05
Maybe regarding the stack, we just had not  time to look into that yet

**Comment by thsig** [comment] 2024-02-08 10:58
Closing this for now, please reopen this if it's still an issue.

**Closed by thsig** 2024-02-08 10:58 UTC
Labels: bug, needs-more-info, triage/accepted
