### ISSUE TITLE
Propagate test return value from `garden run test`

### ISSUE THREAD

**Issue by mitchfriedman** [garden-io/garden#1659] opened 2020-03-02 10:26 UTC
### Current Behavior

Running `garden run test <module> <test>` always returns a 0 exit code, regardless of the return value from the actual test.

### Expected behavior

The `garden run test` command should propagate the status code from the test it ran.

### Reproducible example

Run `garden run test <module> <test>` on a failing test.

### Workaround

Running `garden test` will return the correct status code.

### Suggested solution(s)

Propagate the return value from the test run.

### Additional context

n/a

### Your environment

`garden version`
0.11.5

**Comment by edvald** [comment] 2020-03-02 11:12
This may be a regression, or an oversight. The expected behavior is indeed the intended behavior. As a temporary workaround, you might be able to use the `--output json` flag and parse the result object, but of course that's not ideal in an automated workflow.

**Comment by 10ko** [comment] 2020-03-02 11:54
Assigned to @mitchfriedman since he mentioned he'd like to give it a try at fixing it.
Let us know if you need support!

**Closed** 2020-03-10 15:52 UTC
Labels: bug, priority:high
