### ISSUE TITLE
Local Minikube Getting Started Linux: getaddrinfo ENOTFOUND demo-project.192.168.49.2.nip.io

### ISSUE THREAD

**Issue by RomainBillot** [garden-io/garden#2978] opened 2022-05-31 18:40 UTC
### Current Behavior

On local Minikube, on my Linux computer, running the getting started example is impossible to me. In fact, I can't access frontend and backend services from given neat URL created by garden `demo-project.192.168.49.2.nip.io`
### Expected behavior

I expect the URL to be accessible from my browser (or curl)

### Reproducible example

```
garden call backend
```
Give the output: 
```
getaddrinfo ENOTFOUND demo-project.192.168.49.2.nip.io
```

### Workaround

I didn't found a workaround for now

### Suggested solution(s)

I don't know, I'm a newbie to this k8s cluster world.

### Your environment

* **OS:** Ubuntu 20.04.4 LTS
* **How I'm running Kubernetes:** minikube version: v1.25.2

Garden version: `0.12.40`

**Comment by Orzelius** [comment] 2022-06-27 11:49
Hey, I could not reproduce the issue with the same os and same version of minikube.

In general the url `demo-project.<localhost>.nip.io` will give 404 as this project has no routes for that path. I think if you checked the ingress path that garden gives after running `garden deploy` in the project root it would work (see pic). For example try pinging the backend ingress at `/hello-backend` that's specified [here](https://github.com/garden-io/garden/blob/master/examples/demo-project/backend/garden.yml#L21-L23)

![image](https://user-images.githubusercontent.com/33936483/175934485-32184e81-8fe4-4541-93f6-f3e1b2bd6761.png)

I'm closing this for now, but if the issue persists feel free to reopen

**Closed by Orzelius** 2022-06-27 11:49 UTC
