### ISSUE TITLE
Hot reload 🔥👩🏻‍🚒

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#154] opened 2018-06-06 14:05 UTC
I'd like to discuss and lay out some options and a proposed design for "hot reload", a feature that would allow rapid reload of containers (and by extension any other modules that are transparently run as containers).

**The problem**
Currently our re-deployments always require a re-build and full restart of pods, which can take a long time compared to the built-in live reload that many servers offer in development mode. This is one of the pain-points often associated with containers and can often slow down development substantially.

People apply a number of different "hacks" to get around this, such as running development containers that mount host volumes (only works on local machine), [Telepresence](https://www.telepresence.io) which is interesting but non-trivial for the end-user as well, and probably some other options involving port proxy-ing etc that I can't think of myself.

We'd like to make this as smooth as possible in our framework, so I'd like to lay out a couple of ideas that I've been mulling over.

**Option 1: Automate Telepresence**
I mentioned above that using Telepresence is non-trivial, but I figure many of the steps involved could be abstracted and automated away in the framework. The way it would work (in basic terms) is that we'd derive the appropriate parameters for Telepresence (such as port numbers) automatically from the container configuration and you'd get a command like `garden telepresence my-service`. This would deploy a proxy container in place of the `my-service` container in the cluster, and start a telepresence shell locally on your machine.

This would actually be a rather neat feature, but it does mean you'll need to run the command for each service you're working on, so it's not at all transparent. We'd also need to make sure other runs of `garden deploy/dev/test` don't interfere with the proxy (basically abort deploying unless you use `--force`, something like that).

**Option 2: Sync code to remote volume**
Much the same way we use `rsync` to sync to our build staging directory, we could use it to sync to a container running rsync, on top of a shared volume, which we then mount in the corresponding service container(s). This has the benefit of having the container run in its actual environment, and that we could transparently sync code for any number of services.

This would have to be "opt-in" at the service level. Not all modules would work with this out of the box, and you'd need to configure some specifics. I imagine you'd want something like the following:

```yaml
module:
  type: container
  # ...
  services:
    - name: my-service
      # ...
      hot-reload:
        command: [npm, run, dev]  # the command to run instead of the normal start command
        sync:  # where to sync the module source to
          target: "/app"
```

Some open questions:
1. Do we deploy a module using the hot-reload mechanism by default or not?
2. Do we configure the hot-reload default by environment perhaps?
3. How do we keep track of the "version" that's running when syncing code?
4. What implications does this have in terms of dependencies?

You may note that options 1 and 2 are not mutually exclusive, but we should think about what our preferred path is and what we think would be most valuable. And of course - will there be dragons in our path towards either of these?

Discuss :)

**Comment by thsig** [comment] 2018-06-06 16:09
I'm leaning toward **option 2**, though we might want to use Telepresence for other features (as mentioned above).

It seems simpler, and I get the feeling we'll want more and more control over these things as time goes on. If so, it might be better to avoid locking ourselves into a framework. I don't have a super-strong opinion on it, though.

First impressions regarding the questions:

1. Not sure I'm answering the same question, but I think the hot-reload mechanism should be off by default. E.g. if the user includes static files among those auto-reloaded, they might be surprised to see them changing on the fly when Garden is set to a non-development environment.
2. Yeah, that sounds like a sensible default.
3. Maybe we could add a `.garden/version` file (or several files, when we support several repos) with the VCS version (including the dirty timestamp, if any) that would be used both with and without hot-reloading turned on? The accuracy of the dirty timestamp doesn't really matter to the build system, only the linear ordering of timestamps, so the time the last sync started would be fine.
4. How about this: A hot-reloading should not trigger a full redeploy/rebuild of other hot-reloading Garden-level build dependencies/dependants, but otherwise trigger redeploy/rebuild as usual. However, the auto-reload behaviour when changing a non-hot-reloading module **should** redeploy/rebuild modules regardless of their hot-reload configuration.

**Comment by thsig** [comment] 2018-06-06 16:14
Are there any intricacies to option 2 you'd like to call out for discussion, @edvald?

**Comment by edvald** [comment] 2018-06-06 17:13
Re points 1 and 2, agreed.

Point 3: Not sure storing the VCS version locally helps, but we could instead attach some metadata to the deployment (via ConfigMap or updating annotations on the Deployment). And we could explicitly set an annotation on the Deployment to flag it as a hot-reload deployment.

Point 4: Makes sense, we should just list out the different cases, separately for build and runtime dependencies (which may be the same flow in some cases but not all).

There is one other thing I can think of: What to do when the process that was syncing to the hot-reload process ends? And how do we reliably know it has ended?

**Comment by edvald** [comment] 2018-06-10 22:41
Found this: http://docker-sync.io/

We could either use it directly (although the ruby dependency is slightly annoying), or at least use for reference.

Their wiki also has some useful info, including this: https://github.com/EugenMayer/docker-sync/wiki/Alternatives-to-docker-sync

**Comment by thsig** [comment] 2018-06-13 12:32
A few questions/thoughts:

1. Should we start by supporting hot reloading for containers only? Serverless function support should be easy to add on later, at any rate.
2. What mounting mechanism will we use for the container case? Docker volumes, bind mounts, ...?
3. How do we want hot reloading to fit into our current suite of CLI commands? E.g. when running `garden deploy -w` or `garden build -w`, should modules configured for hot reloading skip the full build / deploy steps (except when config changes, of course)? Do we want to add a new command that only does hot reload watching?

If `deploy -w` and `build -w` skip the full build/deploy steps for hot reloading modules when sources change (barring configuration changes), the user would have to manually end and restart the commands to trigger a build/deploy when the changes they’ve just made demand this.

There could also be keyboard shortcuts for this in the watch-mode commands, but I'm hoping the design will make that unnecessary.

Regarding Garden-level build / service dependencies, changing a module’s `garden.yml` would always result in a restart of the outlying command, so I don’t see a problem with hot reloading leading to an inconsistent state there.

If the module needs to be rebuilt because the user changed the module’s `package.json` or the like, that’s another matter. However, we could add a config directive for “rebuild / redeploy the module when these files / dirs change”, which might address most of the cases where a full rebuild / redeploy of an otherwise hot reloading module would be needed.

Am I missing any version/dependency-related considerations here?

**Comment by edvald** [comment] 2018-06-13 12:41
1. Yes, we should just build this for `container` modules, but that will actually be usable in many cases for other module types which build on top of container modules.

2. I suggest making an rsync server container with a shared volume, that can be mounted to the specified directory in the target container.

3. That's probably the most tricky bit, all the flows and frameworking etc. But generally yes, hot reload should happen instead of the normal build/deploy process. We may want to, at least to start (I figure this will be an experimental feature for a while), have an additional `--hot-reload` - or just `--hot` :P - CLI param to enable the feature where applicable.

One option could be to _always_ do a full build and deploy (i.e. the same flow we currently have) at the start of a command, and hot-reload then taking over for the duration of the running `--watch` command. That way we also sidestep some issues like what happens after the process that's syncing to a container stops.

And yes, we might want to have some additional config options under the `hotReload` key to define what should trigger a full reload. Could probably defer that to a 2nd iteration on the feature though.

**Comment by thsig** [comment] 2018-06-13 12:50
2. & 3. — Yep, sounds good.
> One option could be to always do a full build and deploy (i.e. the same flow we currently have) at the start of a command, and hot-reload then taking over for the duration of the running --watch command. That way we also sidestep some issues like what happens after the process that's syncing to a container stops.

Definitely. Not doing this could lead to various tricky, difficult-to-reproduce inconsistencies.

> And yes, we might want to have some additional config options under the hotReload key to define what should trigger a full reload. Could probably defer that to a 2nd iteration on the feature though.

Yeah, makes sense.

**Comment by eysi09** [comment] 2018-10-21 16:55
@thsig Can we close this one?

**Comment by thsig** [comment] 2018-10-22 09:16
@eysi09 Yeah.

Implemented here: https://github.com/garden-io/garden/pull/291

**Closed by thsig** 2018-10-22 09:16 UTC
Labels: feature, literature
