### ISSUE TITLE
[FEATURE]: ability to define nodeSelectors on container modules

### ISSUE THREAD

**Issue by jalper** [garden-io/garden#4034] opened 2023-03-31 22:51 UTC
## Feature Request

Multiple users have requested the ability to use nodeSelectors on container modules.

### Why do they want to do this? What problem does it solve?

Users often want to stick with the much simpler container module type so they don't need to write full detailed kubernetes manifests, but still need to be able to restrict where their services can run.

### Suggested Implementation(s)

@edvald has proposed a potential `kubernetes-container` extended type that could add more k8s specific fields like this. Other users have also asked about other options like affinities and horizontal pod autoscaling.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by alexkuretz** [comment] 2023-03-31 23:07
Thanks for creating this. One of our specific use cases is around constraining pods to spot vs on-demand nodes in our EKS clusters. Another is around scheduling GPU's for example with `nvidia.com/gpu`.
https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

**Comment by jackvhall** [comment] 2023-04-02 13:16
Thanks @jalper for creating this issue. My organization uses open source garden core and also has the need for some controls over how pods are scheduled into nodes. Exposing `nodeSelector` would be a good way to do this, but alternatively, tolerations would enable us to do what we need.

The issue is that with the current state of maturity of our specific application, converting container module types into k8s module types can be a heavy lift. Typically, what we're looking for is to have dedicated node pools within which only certain applications (end-to-end test executors, which take up _a lot_ of resource for example) can schedule into. In order to make this work we would have to convert _all_ our modules into k8s module types -- not tenable right now. If we could simply apply additional configuration to the k8s module types, this becomes much easier.

**Comment by pepov** [comment] 2023-04-04 13:18
Hey there, similar headache here as well. We typically start with a container module, then disable it (demote to be a build module) and create a kubernetes module to deploy it.

Ideas:
- how about garden exposing us the manifests it used to deploy the container module originally so that we can base off from it (or just write it out to `.garden`)?
- how about garden generate a helm chart based on a configurable template from container modules, which we could use from helm modules right away?

**Comment by edvald** [comment] 2023-04-04 15:11
We do actually have some plans around that, just had to be queued post 0.13.0 (which we're crunching on right now). We basically want to facilitate both conversion from `container` to `kubernetes` (no Helm conversion planned but we could consider it), and to introduce a new `kubernetes-container` type that expands a bit on the more generic `container` type.

All this here is solid feedback and will help work out the finer points! 🙏

**Comment by pepov** [comment] 2023-04-05 07:51
To be fair we are going to play around with these two options first before asking for new features:
- reusable base helm charts like this: https://github.com/garden-io/garden/blob/0.13/examples/vote-helm/api.garden.yml
- reusable config templates like this: https://github.com/garden-io/garden/tree/0.12.51/examples/templated-k8s-container

**Comment by pepov** [comment] 2023-04-17 16:59
Update: base helm chart is nice, but eventually we would want to build charts in order to be able to "ship" them as release artifacts. (Think of on-prem deployments for example)

**Comment by vvagaytsev** [comment] 2023-07-13 11:34
Closing in favor of #4729.

**Closed by vvagaytsev** 2023-07-13 11:34 UTC
Labels: feature request, triage/accepted, community
