### ISSUE TITLE
Task runs do not copy volumeMounts

### ISSUE THREAD

**Issue by khaled** [garden-io/garden#1766] opened 2020-04-02 23:58 UTC
## Bug

I've got a helm module with some tasks in it. The service resource is a deployment that is part of the chart. The pod spec in that deployment mounts a couple of volumes, one from a secret and another from a ConfigMap, which are configuration files that are read by the primary container.

Tasks spin up a new pod, but unfortunately do not seem to copy over the `volumeMounts` and `volumes` referenced by the primary container in the deployment.

I'm stuck because afaict there's no way to specify the same secret + ConfigMap based volumes in the task definitions. And even if it were possible, I probably would not want to duplicate this configuration in the task definitions - ideally they'd be copied over from the deployment.

I suspect tests have the same issue, but have not tried them to confirm.

### Expected Behavior

Task runs create pods with the same volumes and volume mounts as the ones defined in the service resource.

Or maybe instead of creating new pods, the tasks can just exec within the existing pods.

### Workaround

Run `kubectl exec` instead of using garden tasks (and maybe tests) :( 

### Your environment

```
▶ garden --version
0.11.9
```

**Comment by jamesgregorystewart** [comment] 2021-05-24 19:25
This is still an issue as of garden version 0.12.20.

**Comment by eysi09** [comment] 2021-06-01 14:14
Hi @jamesgregorystewart 

Thanks for pointing this out. This one has kind of slipped through the cracks. We'll look into this.

**Comment by tobiasmcnulty** [comment] 2022-06-28 19:20
This would be helpful for us, too.

**Comment by worldofgeese** [comment] 2022-12-22 14:22
I've bumped priority as Tasks should be respecting `volumeMounts` by design and according to our [reference docs](https://docs.garden.io/reference/module-types/kubernetes#tasks-.resource). `volumes` and `volumeMounts` go hand in hand.

**Comment by hassinerhouma** [comment] 2023-02-03 09:56
Still happening as of version 0.12.50 with `garden test`.
This issue, plus the fact of running tests in their own new pod, makes `garden test` unusable in our case.
I would appreciate this getting more attention!

**Comment by Orzelius** [comment] 2023-06-14 09:55
This is fixed in 0.13 with both modules and actions.

**Closed by Orzelius** 2023-06-14 09:55 UTC
Labels: bug, priority:high
