### ISSUE TITLE
Garden does not support openid-connect token authentication

### ISSUE THREAD

**Issue by ITHedgeHog** [garden-io/garden#2311] opened 2021-03-17 10:45 UTC
### Current Behavior

When using Garden against an Azure AKS Cluster which has Azure AD backed RBAC enabled garden commands time out after 15 minutes as shown below:

![image](https://user-images.githubusercontent.com/13481/111453829-e7e70880-870b-11eb-9559-700dc32ac684.png)

This persists until you run a command in kubectl (I use kubectl version) which obtains a new token from the cluster correctly.

### Expected behavior

I expect garden cli to operate the same as kubectl, to fully support the openid-connect token authentication on Azure AKS.

### Reproducible example

1. Set up Azure AKS Cluster backed by Active Directory enabled RBAC
2. Install azure cli tools
3. Run 'az login' to authenticate against Azure Active Directory
4. Run 'az aks get-credentials --name <cluster-name> --resource-group <resource-group-name>'
5. Test connection by running 'kubectl version'
6. Deploy https://github.com/garden-io/garden/tree/master/examples/demo-project to Kubernetes
7. Leave for 16 minutes
8. Then run a garden command such as garden dev or garden deploy

### Workaround

Running a kubectl command every 15 minutes to refresh the token, then restarting garden cli as required.

### Suggested solution(s)

garden would either need to call kubectl under the hood to get an updated token on an API failure, or update garden itself to support the relevant authentication mechanisms.

Relevant Kubernetes documentation: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens

Azure Authentication package in Kubernetes: https://github.com/kubernetes/kubernetes/blob/cea1d4e20b4a7886d8ff65f34c6d4f95efcb4742/staging/src/k8s.io/client-go/plugin/pkg/client/auth/azure/README.md

### Additional context

This bug is a blocker for my team, we were looking to adopt garden and look at garden-enterprise however that project is on hold until this issue is resolved. It is a complete deal breaker to have to stop garden, run kubectl and set of garden again.

### Your environment

* **OS:** Windows 10
* **How I'm running Kubernetes:** Azure AKS with Azure AD RBAC

`garden version` 0.12.19

**Comment by eysi09** [comment] 2021-04-08 12:39
Hi @ITHedgeHog 

Apologies for the late reply! We've been a little swamped lately and this one slipped through the cracks. I'll run this by the team and report back with a timeline ASAP.

**Comment by eysi09** [comment] 2021-04-08 12:53
This might actually have been fixed in version `0.12.20`, where we updated the k8s client lib, which generally handles this sort of thing. Would you mind giving that a spin and see if you can use Garden for more than 16 minutes?

**Comment by ITHedgeHog** [comment] 2021-04-08 13:21
Hi @eysi09 I've been testing over the past few days, it is not fixed in 0.12.20 I've restored to putting a 10 minute scheduled task on my machine to run kubectl version to keep things working

**Comment by edvald** [comment] 2021-04-08 13:27
Ok, we might need to flag or fix this in the upstream library (https://github.com/kubernetes-client/javascript). I'll see if I can work out where/why the problem lies, if it's an upstream bug, Garden bug or a missing capability in the client lib.

**Comment by ITHedgeHog** [comment] 2021-04-08 13:44
Yeah, I've been having a look at that trying to find more information for you, but to be honest I'm a little lost with it! :)

If I find anything that seems relevant I'll flag it here :)

**Comment by eysi09** [comment] 2021-04-15 10:00
@twelvemo, didn't you bump into something similar when setting up the Azure container image?

**Comment by twelvemo** [comment] 2021-04-15 10:05
Yes. There is a tool called kubelogin (https://github.com/Azure/kubelogin) that might help. Have you tried that one out @ITHedgeHog ?

**Comment by ITHedgeHog** [comment] 2021-04-16 16:25
I'd not, I'll take a look at this next week. Thanks @twelvemo 👍

**Comment by eysi09** [comment] 2021-04-20 10:00
I'm closing this as a duplicate of #2330. We can continue the conversation there :)

**Closed by eysi09** 2021-04-20 10:00 UTC
Labels: bug, priority:high, provider/k8s
