### ISSUE TITLE
Bug: Terraform module logs output sensitive terraform outputs in plain text

### ISSUE THREAD

**Issue by ashwiren** [garden-io/garden#3550] opened 2023-01-19 01:38 UTC
### Current Behavior

Using terraform outputs:
```
output "password" {
  value     = "somesecret"
  sensitive = true
}
```
and `garden -l=silly -o=yaml` the output will be printed in plain text in the console logs.

### Expected behavior

The output should be replaced with something like `<sensitive>`

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`

**Comment by stefreak** [comment] 2023-02-08 13:10
@raywonkari awesome, please feel free to do that! The problem should be somewhere in the terraform plugin code: https://github.com/garden-io/garden/tree/main/plugins/terraform

I will be very happy to help you if you have any questions and will also be happy to review a PR. See also our contributor guide on how to build & test garden: https://github.com/garden-io/garden/blob/main/CONTRIBUTING.md#developing

**Comment by stefreak** [comment] 2023-02-08 13:12
At a first glance, it might be that it's easier to eliminate the log message altogether instead of replacing sensitive values in the output. I would also accept a change like that.

**Comment by stefreak** [comment] 2023-02-09 11:01
I see, the thing is that the provider outputs need to contain the sensitive values, and users need to be able to use them e.g. in a kubernetes module later, for example to connect to the database.

So I think we need to find all the places where it might be logged, or add a way to mark provider outputs as sensitive and prevent logging them in the framework. Thank you for the investigation, and I'm glad to continue to help, but feel free to pick another issue as well (maybe the ones tagged with "good first issue") if this one gets too complicated. Thank you so much for the effort! 🥇

**Comment by ashwiren** [comment] 2023-02-09 23:57
I think the key point is `-l=silly -o=yaml`

**Comment by stefreak** [comment] 2023-02-10 07:30
@ashwiren can you share the (sanitized) log message with us, and the full garden command that you were executing (e.g. garden -l=silly -o=yaml deploy), and maybe even an outline of your provider configruation in project.garden.yml. This would 
be of great help finding the culprit

**Comment by ashwiren** [comment] 2023-02-10 07:31
Yep I'll see if I can create a reproducible example

**Comment by stefreak** [comment] 2023-02-10 08:30
@ashwiren you can also try to see if the output of the command `garden get debug-info` is something you could share with us. it's basically a zip file with the project configuration files. If you want to share this with us, make sure it does not contain sensitive information

**Comment by ashwiren** [comment] 2023-02-14 02:48
https://github.com/ashwiren/gardenexample

**Comment by ashwiren** [comment] 2023-02-14 02:50
Appears to output passwords etc in plain text even with just `garden --yes -o=yaml deploy`

**Comment by ashwiren** [comment] 2023-02-14 03:06
same problem exists with -o=json

**Comment by stefreak** [comment] 2023-02-15 07:25
@ashwiren @raywonkari sorry for the back-and-forth on this; I have now thought about this again, and asked the original authors (as I am still quite new in the team).

The options `-o=yaml` and `-o=json` are meant to be used in cases where another program calls garden, e.g. a script or some other piece of software. As the module outputs might be used by these scripts, we do not sanitize the output by design, as the scripts might need to use these values.

I will close this issue for now, but I am still very interested in what's behind the use of the `-o=json` and `-o=yaml` flags – are you using garden in a script? Maybe your script needs to become aware that this value is sensitive, to in turn prevent that it logs it? In that case I would be open to a feature request to change the schema of our json and yaml outputs, to include a flag wether or not the value that is part of an output is sensitive.

@ashwiren I'd be very happy if you could elaborate on your use case.

**Comment by ashwiren** [comment] 2023-02-15 07:30
@stefreak We use -o=yaml in CI as it gives detailed information which is immediately useful when errors happen, eg gitlab agent has a weird timeout etc.

I'll need to investigate alternative ways of getting more verbose outputs from garden if this is working as intended.

**Comment by stefreak** [comment] 2023-02-15 08:12
That's very interesting, could you share some error output with us that you like better in `-o=yaml` compared to, say, `-l=verbose` + a step that does `cat .garden/error.log` on failure? 

Our goal is definitely that error messages are good by default, and we'll try to improve this.

**Comment by ashwiren** [comment] 2023-02-16 00:43
We use logger-type=basic via env var in CI

snippet from .gitlab-ci.yml
```
  variables:
    GARDEN_LOGGER_TYPE: basic
```

example error:
```
errors:
  - detail:
      results:
        deploy.xxx:
          type: deploy
          description: deploying service 'xxx' (from module 'xxx')
          key: deploy.xxx
          name: xxx
          error:
            shortMessage: >-
              Command failed with exit code 1:
              /root/.garden/tools/kubectl/hash123/kubectl
              --context=aaa/bbb/configuration/deployment:yyy
              apply --output=json -f -
            command: >-
              /root/.garden/tools/kubectl/hash123/kubectl
              --context=aaa/bbb/configuration/deployment:yyy
              apply --output=json -f -
            exitCode: 1
            stdout: ''
            stderr: >-
              Warning: autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated
              in v1.22+, unavailable in v1.25+; use autoscaling/v2
              HorizontalPodAutoscaler
              Error from server: error when retrieving current configuration of:
              Resource: "policy/v1, Resource=poddisruptionbudgets",
              GroupVersionKind: "policy/v1, Kind=PodDisruptionBudget"
              Name: "xxx", Namespace: "zzz"
              from server for: "STDIN": GitLab Agent Server: HTTP->gRPC: failed
              to read gRPC response: rpc error: code = Canceled desc = context
              canceled. Trace ID: hash456
            all: >-
              Warning: autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated
              in v1.22+, unavailable in v1.25+; use autoscaling/v2
              HorizontalPodAutoscaler
              Error from server: error when retrieving current configuration of:
              Resource: "policy/v1, Resource=poddisruptionbudgets",
              GroupVersionKind: "policy/v1, Kind=PodDisruptionBudget"
              Name: "xxx", Namespace: "zzz"
              from server for: "STDIN": GitLab Agent Server: HTTP->gRPC: failed
              to read gRPC response: rpc error: code = Canceled desc = context
              canceled. Trace ID: hash456
            failed: true
            timedOut: false
            isCanceled: false
            killed: false
          startedAt: '2023-02-13T08:50:21.143Z'
          completedAt: '2023-02-13T08:50:24.077Z'
          batchId: 676a0b31-7788-42d7-95f7-8a7ff10444db
          version: v-e73ec71ba6
    type: runtime
```

I don't have that error captured without -o=yaml, its not reproducible it just happens sometimes with the gitlab cluster agent.

**Comment by stefreak** [comment] 2023-02-16 07:01
@ashwiren The error detail can also be found in .garden/error.log after a command has failed. It is also in yaml format. Would it be sufficient for you to run garden with `-l=verbose` (log level verbose) and then alter you gitlab-ci config to something like:

```
test_job:
  # ...
  after_script:
    - >
      if [ $CI_JOB_STATUS == 'success' ]; then
        echo 'This will only run on success'
      else
        echo 'This will only run when job failed or is cancelled. Here is the .garden/error.log'
        cat .garden/error.log
      fi
```

Would you agree that we should print the error log automatically with log level verbose and upwards?

**Comment by ashwiren** [comment] 2023-02-16 07:04
I think there should just be a --ci switch that does a bunch of sensible defaults

**Comment by stefreak** [comment] 2024-01-25 14:45
Closing this in favor of #5666

**Closed** 2024-01-25 14:45 UTC
Labels: discussion, provider/terraform, community
