### ISSUE TITLE
`garden del env` can't finish

### ISSUE THREAD

**Issue by wojtkowiak** [garden-io/garden#1740] opened 2020-03-27 15:35 UTC
reporting a bug as suggested in #1734 

## Bug

`garden del env` stopped working for me as soon I started using the persistenvolumeclaim, I can see during deleting `No delete service handler available for module type persistentvolumeclaim` and the PersistentVolume I have declared as k8 yml (module type kubernetes) just hangs indefinitely presumably because the volume is still claimed. After `kubectl delete pvc my-pvc` another try of garden del env passes.

### Current Behavior

`garden del env` hangs indefinitely.

### Expected behavior

`garden del env`, deletes the PVC and allows PV to be deleted as well.

### Reproducible example

You just need to declare a PV in k8. I can create a small repro repo if needed.

### Workaround

`kubectl delete pvc <my_pvc>` before `garden del env`

### Suggested solution(s)

Not a k8 expert but probably PVC should be deleted during `del env`

### Your environment

OSX
garden/kubectl/docker at newest

**Comment by wojtkowiak** [comment] 2020-05-27 07:55
Still relevant for me :)

**Comment by thsig** [comment] 2022-04-14 12:18
We haven't seen any reports of this recently, so we're closing this for now. Feel free to reopen if this is still an issue!

**Comment by alexkuretz** [comment] 2023-08-01 18:48
This is an issue for me as well. The project utilizes an existing EFS share for long-lived storage, not dynamically provisioned. I haven't found a PersistentVolume module in garden so created a Kubernetes module to mount the PV, and then use PersistentVolumeClaim modules to attach EFS directories to the container. This all works fine for deploying, the problem is with trying to delete the environment. Garden won't complete the cleanup because it doesn't remove the PVC's, and Kubernetes won't delete the PV until the PVC's have released the PV. The PV is left in a "Terminating" state and the delete hangs waiting. Manually deleting the PVC's allows the delete to finish.

`No delete service handler available for module type persistentvolumeclaim`

This is an issue in both 0.12.63 and 0.13.9, using both modules and actions. I've got a thread going in our Garden slack channel.

**Comment by vvagaytsev** [comment] 2023-08-02 09:47
An implementation idea from Jon:
> The `persistentvolumeclaim` module/action type is missing a delete handler. The simple fix is just to add it in.

**Closed** 2023-08-11 08:26 UTC
Labels: bug
