### ISSUE TITLE
0.13: [Bug]: `quickstart-example`, when run on k3s, fails on first deploy only

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#4460] opened 2023-05-26 12:41 UTC
### Current Behavior

One issue I encountered was the postgres deploy failing and not re-trying (this happened again on a brand new Cloud Shell and I don't know why):

![image](https://github.com/garden-io/quickstart-example/assets/59834693/10071483-1334-457d-ac63-1b2205733860)

I just ran `deploy` again, which successfully deployed all services the second time:

![image](https://github.com/garden-io/quickstart-example/assets/59834693/d908969e-6d2d-469f-8490-9318f6b5871e)

_Originally posted by @worldofgeese in https://github.com/garden-io/quickstart-example/issues/6#issuecomment-1563126594_

### Reproducible example

[![Open in Cloud Shell](https://gstatic.com/cloudssh/images/open-btn.svg)](https://shell.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https%3A%2F%2Fgithub.com%2Fgarden-io%2Fquickstart-example.git&cloudshell_open_in_editor=project.garden.yml&cloudshell_tutorial=tutorial.md&show=ide&ephemeral=true)

### Workaround

Run `deploy` a second time.

**Comment by ShankyJS** [comment] 2023-06-02 15:40
@Orzelius, this problem is also present on Killercoda example; I'm using Ubuntu 18.04 with a k3s cluster;

First deploy will fail and then the second deployment succeeds, 

To reproduce this, just access the Killercoda environment and follow the steps until the `deploy --forward` you will notice how the demo fails with the same error that Tao has.

https://killercoda.com/shankyjs/course/scenarios/getting-started

I couldn't reproduce this locally

**Comment by vvagaytsev** [comment] 2023-06-19 10:28
@worldofgeese I can't reproduce this, because Cloud Shell init fails when it tries to clone the remote repo:
<img width="405" alt="Screenshot 2023-06-19 at 12 27 40" src="https://github.com/garden-io/garden/assets/10628074/7804cd3c-e2a3-4c09-9a83-ccb5e47b84ed">

This this a know issue?

**Comment by worldofgeese** [comment] 2023-06-19 11:05
> @worldofgeese I can't reproduce this, because Cloud Shell init fails when it tries to clone the remote repo (I tried 3 times): <img alt="Screenshot 2023-06-19 at 12 27 40" width="405" src="https://user-images.githubusercontent.com/10628074/246803224-7804cd3c-e2a3-4c09-9a83-ccb5e47b84ed.png">
> 
> This this a know issue?

The link was fixed "in prod" (on our docs site). I've now fixed it for the Cloud Shell button in this issue. Can you try again?

**Comment by worldofgeese** [comment] 2023-06-19 11:06
@vvagaytsev

**Comment by vvagaytsev** [comment] 2023-06-19 11:11
@worldofgeese thanks! Now I can open the project in the Cloud Shell. By the way, `garden` is not recognized as a command there. And the `start.sh` has no permission to be executed. I had to modify it manually to get it working.

**Comment by worldofgeese** [comment] 2023-06-19 11:21
@vvagaytsev did you follow along with the tutorial on the right sidepane? I just tried and it works.

![image](https://github.com/garden-io/garden/assets/59834693/30913c41-3eb7-4514-9785-fee6c7dbcfd7)

![image](https://github.com/garden-io/garden/assets/59834693/41e42adb-0b7e-439c-9d89-abd90cee5cd9)

**Comment by vvagaytsev** [comment] 2023-06-20 06:15
The fix will be released today in Garden `0.13.3`. We'll have to update the Garden version in the example after the release.

**Comment by worldofgeese** [comment] 2023-06-21 07:22
@vvagaytsev thank you so much for this fix! 💚

**Comment by worldofgeese** [comment] 2023-07-03 12:06
@vvagaytsev I have reproducible examples and guides for setting up test environments for k3s, k3d, and Rancher Desktop together with error messages for each at #4528. if you use Multipass on macOS, you can spin up an Ubuntu VM very easily [with this tutorial](https://multipass.run/docs/mac-tutorial) to test k3s and k3d. Rancher Desktop is macOS compatible OOTB.

**Closed** 2023-07-05 11:17 UTC
Labels: bug, 0.13
