### ISSUE TITLE
Dirty timestamp doesn't get updated on untracked files

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#326] opened 2018-10-10 07:36 UTC
As a result, Garden can't detect changes in new modules that haven't been added/commited to the git repo.

**Comment by drubin** [comment] 2018-10-10 09:21
Does this relate to #324 ? 

Seems like they have a similar issue that we use git to determine these values?

**Comment by edvald** [comment] 2018-10-10 10:06
It is related in a sense, in that this is checked in the VCS handler. We should fix the two issues at the same time.

**Comment by edvald** [comment] 2018-10-26 18:45
Figured out what the issue is. We do catch untracked _files_, but the issue comes up with new untracked module _directories_. Working on a fix.

**Comment by edvald** [comment] 2018-10-26 18:57
Actually, I don't think this is an issue. The only case not currently handled by the code (at least after #324 is fixed) is when you add a new _empty_ module directory. In that case, the commit hash will be that of the parent directory/repo, and no dirty timestamp set, but I don't think that's a problem. If there are untracked and/or modified files in the directory, those are used to return the dirty timestamp. 

Closing this, please re-open if I missed something.

**Closed by edvald** 2018-10-26 18:57 UTC
Labels: bug
