### ISSUE TITLE
Failed resolving provider minikube 1.17.0

### ISSUE THREAD

**Issue by gloelmat** [garden-io/garden#2234] opened 2021-02-01 11:47 UTC
### Current Behavior

After updating minikube from 1.16.0 to 1.17.0 we receive the following error when running garden commands like

garden run/test/deploy etc.

```
Failed resolving provider local-kubernetes. Here is the output:   Unable to load kubeconfig: Error: Command "/home/runner/.garden/tools/kubectl/804c71b3e6ad5976/kubectl --context=minikube config view --raw" failed with code 1:    error: converting to : type names don't match (Unknown, RawExtension), and no conversion 'func (runtime.Unknown, runtime.RawExtension) error' registered.    error: converting to : type names don't match (Unknown, RawExtension), and no conversion 'func (runtime.Unknown, runtime.RawExtension) error' registered.
```

### Workaround
Pinning version to minikube 1.16.0
We would like to update to minikube 1.17

### Your environment
macOS catalina 10.15.3
Kubernetes minikube 1.17.0
garden 0.12.15

**Comment by jeremiahlewis-vw** [comment] 2021-02-12 07:22
I can confirm this issue in my machine (which affects the latest stable version of minikube).

**Comment by edvald** [comment] 2021-02-12 10:35
Are you on the latest Garden version? We updated the kubectl version in that one, and I ran tests with that myself, couldn't reproduce.

**Comment by jeremiahlewis-vw** [comment] 2021-02-12 11:35
Works great. Should have rechecked the newest version before pinging. Thanks!

**Comment by edvald** [comment] 2021-02-12 11:36
No worries, I should have commented on the issue! I'll close this then, thanks for confirming :)

**Closed by edvald** 2021-02-12 11:36 UTC
