### ISSUE TITLE
garden cleanup-cluster-registry not working as expected

### ISSUE THREAD

**Issue by kcooi** [garden-io/garden#2172] opened 2020-12-18 10:06 UTC
## Bug
When running `garden --env=default.remote plugins kubernetes cleanup-cluster-registry`, keep hitting error below:
*Error: Could not find running pod for Deployment/garden-docker-registry*

### Current Behavior

Behavior 1
<img width="1438" alt="behavior2" src="https://user-images.githubusercontent.com/7358403/102601467-298f0400-415b-11eb-9c77-2ace95e9be6d.png">

Behavior 2
<img width="1052" alt="issue1" src="https://user-images.githubusercontent.com/7358403/102601434-20059c00-415b-11eb-8a12-a9ce7c8adc3e.png">

### Expected behavior
Able to clean up diskspace successfully

### Your environment
`garden 0.12.11`
`EKS 1.15`

**Comment by eysi09** [comment] 2020-12-22 08:03
Hi @kcooi! 

Looks like this is a duplicate of #1635 which we closed because we were unable to reproduce and the user that originally reported it wasn't running into it anymore. 

Is this happening consistently on your end? Also, have you tried running initialising the system services recently, with:

```
garden plugins kubernetes cluster-init --env=default.remote
```

**Comment by kcooi** [comment] 2020-12-23 02:10
Hi @eysi09
The issue does happen consistently and regularly. Out of 10 times this week, There is 1 time only I manages to find registry pod and perform garbage collection (as the screenshot below).

Is there anything we can do from our end like uninstall the garden services, and rerun `garden plugins kubernetes cluster-init --env=default.remote'?

<img width="647" alt="2020-12-23 10_05_28-garden-registry-cleanup (#926157792) · Jobs" src="https://user-images.githubusercontent.com/7358403/102950923-99f4a700-4506-11eb-8d1c-7bb2e4c2d1a9.png">

**Comment by eysi09** [comment] 2021-04-14 22:27
Apologies for the late reply on this one. Completely slipped through the cracks. One workaround is simply to not use the in-cluster registry but rather an [external deployment registry](https://docs.garden.io/guides/in-cluster-building#configuring-a-deployment-registry). It scales a lot better and is generally our recommended approach. Another added benefit is cache sharing across clusters. 

That being said, we should of course get to the bottom of this. I'll close this issue though as a duplicate of the more recent #2274.

**Closed by eysi09** 2021-04-14 22:27 UTC
Labels: bug, needs-more-info
