### ISSUE TITLE
Crash: highlight is not a function

### ISSUE THREAD

**Issue by dlcd** [garden-io/garden#5478] opened 2023-11-24 22:14 UTC
### Error message

TypeError: highlight is not a function
    at highlightYaml (file:///home/xxxxxx/.local/share/garden/1700862965-06mkxv1.r/rollup/garden.mjs:214637:12)
    at renderData (file:///home/xxxxxx/.local/share/garden/1700862965-06mkxv1.r/rollup/garden.mjs:214757:16)
    at file:///home/xxxxxx/.local/share/garden/1700862965-06mkxv1.r/rollup/garden.mjs:214675:40
    at Array.map (<anonymous>)
    at combineRenders (file:///home/xxxxxx/.local/share/garden/1700862965-06mkxv1.r/rollup/garden.mjs:214675:22)
    at formatForTerminal (file:///home/xxxxxx/.local/share/garden/1700862965-06mkxv1.r/rollup/garden.mjs:214781:26)
    at TerminalWriter.write (file:///home/xxxxxx/.local/share/garden/1700862965-06mkxv1.r/rollup/garden.mjs:215151:21)
    at RootLogger.log (file:///home/xxxxxx/.local/share/garden/1700862965-06mkxv1.r/rollup/garden.mjs:309480:24)
    at CoreLog.log (file:///xxxxxx/.local/share/garden/1700862965-06mkxv1.r/rollup/garden.mjs:214937:19)
    at CoreLog.info (file:///home/xxxxxx/.local/share/garden/1700862965-06mkxv1.r/rollup/garden.mjs:214988:21)

### What did you do?

**Command:** garden get status

### Your environment

**OS:** Ubuntu 20.04.6
* **How I'm running Kubernetes:** k3s
* **Garden version:** garden version: 0.13.21

### Frequency

Happens every time command is executed since 0.13.20.

### Workaround

Revert back to 0.13.19

### Additional context

Also occurs in WSL 2 (Ubuntu 22.04)

**Comment by vvagaytsev** [comment] 2023-11-24 22:28
Thanks for reporting this, @dlcd!

This issue is caused by switching to ESM and new machinery for building Garden binaries. Both changes were released in the version 0.13.20. We have already created #5442. Please follow that issue to track the progress.

Closing this a duplicate of #5442.

**Closed by vvagaytsev** 2023-11-24 22:28 UTC
Labels: bug, crash
