### ISSUE TITLE
Disable template string mode apply to module

### ISSUE THREAD

**Issue by truonghdpk** [garden-io/garden#2903] opened 2022-04-16 10:04 UTC
### Current Behavior

I want to disable template string mode cause it makes me can't apply config with my own special character that makes garden template misunderstanding
### Expected behavior

Should ignore template strings in my config file

### Your environment
- kubernetes module
garden.yaml
```
kind: Module
description: My server insight service
type: kubernetes
name:service-client
files:
  - deployment.yaml
  - configmap.yaml

```

configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-client-configmap
data:
  entrypoint.sh: | 
    #!/usr/bin/env bash
    if [[ -z "$GRAB_URL" ]]; then
        echo "Must provide GRAB_URL in environment" 1>&2
        exit 1
    fi
```

output
```
Failed deploying service 'serivce-client' (from module 'service-client'). Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Invalid template string (apiVersion: v1
kind: ConfigMap
met…): Unable to parse as valid template string.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1 deploy task(s) failed!
```

**Comment by Orzelius** [comment] 2022-05-12 14:29
Could not reproduce, worked as expected for me. This is my setup -> https://github.com/Orzelius/garden-tests-1
`garden deploy` output:
```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🌍  Running in namespace default.default
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✔ providers                 → Getting status... → Done
   microk8s                  → enabling required addons (dns, registry, storage, ingress)
✔ service-client            → Deploying version v-47bf42e67a... → Done (took 2.2 sec)
   ℹ service-client            → Resources ready

Done! 
```

I have a feeling your k8s configmap file has a name that garden picks up (ending in `.garden`) or something similar.

Please feel free to add more info or try out my example and see if you get different results. If so I'd love the log output with the `-l5` flag that gives a lot of info

**Comment by thsig** [comment] 2022-06-16 09:34
Closing this one for now—if this comes up again, or if there's more info about how to reproduce it, feel free to reopen it.

**Closed by thsig** 2022-06-16 09:34 UTC

**Comment by oakeyc** [comment] 2022-10-27 19:05
Hello! I am running into the same issue. I want to use a configmap, but I don't want garden to try to render it because garden rendering will fail if I use characters that make it not a valid _garden_ template string. But I just want to place arbitrary configurations in my configmap.

This is an example:
```yaml
apiVersion: v1
data:
  file.conf: |
    ${record.dig("value")}
kind: ConfigMap
metadata:
  name: mymap
```

And the output:
```
Invalid template string (apiVersion: v1
data:
  file.conf: …): Unable to parse as valid template string.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1 deploy action(s) failed!
```

and the error log says:
```text
[2022-10-27T19:02:58.511Z] Error: Invalid template string (apiVersion: v1\ndata:\n  file.conf: …): Unable to parse as valid template string.
    at resolveTemplateString (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/template-string/template-string.ts:200:11)
    at $resolveTemplateStrings (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/template-string/template-string.ts:215:15)
    at /snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/util/profiling.ts:191:20
    at Object.resolveTemplateStrings (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/plugin-context.ts:123:36)
    at /snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/plugins/kubernetes/kubernetes-module/common.ts:103:28

Error Details:

err:
  type: template-string
```

What I would like it to be able to tell garden to not even try to render my configmap. Because my work around is to deploy the configmap manually with kubectl to my cluster, and then reference it in my other manifests.

Please let me know if you'd like any more details. Thanks!

**Comment by vvagaytsev** [comment] 2022-11-22 14:59
Thanks for raising this @oakeyc! Have you checked the suggestions from the [comment above](https://github.com/garden-io/garden/issues/2903#issuecomment-1125067140)?

What was the filename of your configmap config file? Please make sure it didn't end with `.garden.y(a)ml`.
