### ISSUE TITLE
[FEATURE]: command completion 

### ISSUE THREAD

**Issue by exocode** [garden-io/garden#2463] opened 2021-06-30 07:39 UTC
### Background / Motivation

I am one of that guy, hitting the "tab"-button a lot.

### What should the user be able to do?

write `garden`+ press `tab` to complete and suggest commands

### Why do they want to do this? What problem does it solve?

devs are lazy and wont read manuals, so they should get suggestions of the current possible commands.

### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by thsig** [comment] 2021-07-01 10:21
Yeah, this would be really great! We've been discussing this internally recently, hopefully we'll get around to implementing something of the sort soon.

**Comment by eysi09** [comment] 2021-07-15 08:58
Closing as a duplicate of #2344.

**Closed by eysi09** 2021-07-15 08:58 UTC
Labels: feature request
