### ISSUE TITLE
Custom exec commands are executed in the current directory

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#2841] opened 2022-03-08 14:31 UTC
### Current Behavior

I have a custom command that runs a local script, something like:

```
# In <project-root>/custom-commands.garden.yml
kind: Command
name: my-command
exec:
  command: [./scripts/my-script.sh]
```  

If I run it in from the project root the command works as expected.

If I run it from a child dir, I get:

```console
Command exited with code undefined
```

I'm assuming we're not exec-ing the script from the location of the `custom-commands.garden.yml` file.

Also, I would expect a better error. 

I'm on latest master.

**Comment by vvagaytsev** [comment] 2022-06-30 09:38
@eysi09 should we always consider the project root as a `cwd` when we run the commands?

**Comment by vvagaytsev** [comment] 2022-11-23 14:05
Closing as a duplicate of #3151.

**Closed by vvagaytsev** 2022-11-23 14:05 UTC
Labels: bug, devex, getting-started
