### ISSUE TITLE
Endless graph resolving loop

### ISSUE THREAD

**Issue by ShavaShav** [garden-io/garden#3731] opened 2023-02-09 21:33 UTC
### Current Behavior

When running `garden deploy --watch`, making a code change can cause garden to enter an endless loop:

![garden-resolve-repeat](https://user-images.githubusercontent.com/17697598/217942405-8d29066a-3b19-4050-8a37-5da9cdda1546.gif)

I've let it run for a long time but never gets any further.

### Expected behavior

Graph only resolves once and then re-deploys (or hot reloads) the changes

### Reproducible example

I don't have a reproducible example (project I'm using garden for is proprietary). I'll try to create one later but I was hoping this is a known issue.

### Workaround

Kill the garden process and restart it, which causes a redeploy.

### Suggested solution(s)

I'm not sure, I haven't dug into the implementation at all. Possibly exposing more logging about what garden is doing might help me to debug the issue if it's related to my modules.

### Additional context

We use a lot of kubernetes and helm modules, which have build dependencies on images built from container modules.

### Your environment

* **OS:** Ubuntu 20.04
* **How I'm running Kubernetes:** minikube

`garden version` : 0.12.51

**Comment by stefreak** [comment] 2023-02-10 08:55
Hello @ShavaShav I have never seen this before. If it's too much time to create an example, you could also share the (sanitized: might contain secrets) output with the option `-l5` (for silly-loglevel) and the zip file that `garden get debug-info` generates (please have a look first if it contains sensitive information and remove it). We can also get in touch and exchange email addresses if you don't want to share this zipfile publicly.

**Comment by stefreak** [comment] 2023-02-10 08:56
@ShavaShav can you also tell us, if this is something that happened after updating garden, or if it is something that started to happen after changing your garden configuration?

**Comment by stefreak** [comment] 2023-02-13 08:05
Removing triage/accepted and adding needs-more-info labels, because it's almost impossible to work on this without ability to reproduce the issue.

Additional side note: @thsig mentioned that the issue might be confined to 0.12 as the file watcher functionality has been removed in 0.13

**Comment by ShavaShav** [comment] 2023-02-13 17:13
Here is the output for a couple loops with the `-l5` option. I've just renamed all the modules and directories used:
[garden-resolve-loop.log](https://github.com/garden-io/garden/files/10724552/garden-resolve-loop.log)

Garden seems to be using a lot of memory while this is happening:
![image](https://user-images.githubusercontent.com/17697598/218520596-c4947844-f72a-44de-a62a-115b6c7b7e53.png)

I'll upload the zip from `garden get debug-info` later when I get some free time (it's going to take me a bit to remove all of the sensitive info there)

**Comment by ShavaShav** [comment] 2023-02-14 00:23
I'm going to close this as I think the issue is on my end. I had some modules that weren't caching properly. 

A couple of my exec modules (that have a lot of dependants) weren't defining a statusCommand, or had an error in the status command which caused them to build+deploy every time. Also, I was using `exclude/include: [mydir]` instead of `exclude/include: [mydir/**/*]` in a couple spots which seems to be incorrect.

Still confused why it was spamming the resolving modules message, but I'm not seeing the build up anymore after fixing the above issues. Thanks for the quick response though!

**Comment by stefreak** [comment] 2023-03-06 13:49
@ShavaShav I would like to make Garden more robust.

I think it would be better if Garden would print an error message, instead of the infinite loop in the module resolution.

We will have a look at the logs; If you find the time, it would be a great service to the community if you could come up with a reproducable example of this behaviour using exec modules.

**Comment by vvagaytsev** [comment] 2023-07-13 11:13
There is no repro to improve the error messaging. Closing this. Feel free to reopen if you have a good repro.

**Closed by vvagaytsev** 2023-07-13 11:13 UTC
Labels: bug, needs-more-info
