### ISSUE TITLE
sudo: garden: command not found

### ISSUE THREAD

**Issue by marcus-sa** [garden-io/garden#907] opened 2019-06-28 07:43 UTC
### Current Behavior
Unable to run `garden get status` as instructed in your Quick Start guide due to you not supporting sudo:

```sh
$ sudo garden get status
sudo: garden: command not found
```

sudo is required when using minikube with no drivers https://github.com/kubernetes/minikube/issues/3760 

### Expected behavior
Being able to run `garden` as sudo user.

### Environment

`garden version`: 0.10.0

**Comment by edvald** [comment] 2019-06-28 14:57
Hey @marcus-sa. I believe the issue is not that Garden can't be run as sudo, but rather that `sudo garden` can't find the `garden` binary. If you run `sudo <full-path-to-garden>` or symlink `/usr/local/bin/garden` to where you have Garden installed, it should work fine.

I'm curious though, why do you need to run Garden with sudo?

**Comment by marcus-sa** [comment] 2019-06-28 15:31
@edvald hey you're probably right.
As I wrote, starting minikube with no driver's lovally requires sudo explicitly for accessing its config file in ones home directory.
Even though I ran `chmod -R 777 .` on it, unfortunately still failed.

This happens because
https://github.com/garden-io/garden/blob/ed0233b7b59d25686f9e1ca8216a71543974004b/garden-service/src/plugins/kubernetes/local/minikube.ts#L16
Isn't supposed in a local environment with no driver's specified, even though it uses docker as the container.

See these issues:
https://github.com/kubernetes/minikube/issues/2443
https://github.com/GoogleContainerTools/skaffold/issues/112

**Comment by edvald** [comment] 2019-06-28 15:38
Ah, interesting. I guess we'd need to explicitly catch that error message or otherwise check which VM driver is in use. Should be easy to do, I'll flag it for our next update.

**Comment by eysi09** [comment] 2019-07-08 14:01
Fixed with #910 (assuming the original problem with sudo was a none-issue).

**Closed by eysi09** 2019-07-08 14:01 UTC

**Comment by ghostnet2000** [comment] 2023-12-15 10:20
cd to where you have Garden installed, and run chmod +x garden
