### ISSUE TITLE
Artifacts are duplicated when using multiple source/target tuples with different targets 

### ISSUE THREAD

**Issue by lucas-sonnabend** [garden-io/garden#1781] opened 2020-04-07 13:59 UTC
## Feature Request

It looks like at the moment garden only supports a single artifact target properly, I would like to define several source/target tuples, each copying artifacts from the source to a distinct target.

At the moment when you declare several targets and sources all artifacts go into all target directories

### Background / Motivation
I defined artifacts like this
```
    artifacts:
      - source: /tests/cypress/videos_copied/*
        target: test-results/cypress/videos
      - source: /tests/cypress/logs/*
        target: test-results/cypress/logs
      - source: /tests/cypress/snapshots/*
        target: test-results/cypress/snapshots
```
And I ended up with logs, snapshots and videos in all target directories, which made it really annoying to explore them

The documentation should also reflect this behaviour 

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by edvald** [comment] 2020-04-07 14:06
This actually appears to be a bug. The intended behavior you describe is pretty much how it was intended to begin with. I can even see the issue immediately in the code, the different copy procedures share the same temp directory, which was not the idea but was missed in testing. I'll re-flag it accordingly, and we can fix it.

**Comment by lucas-sonnabend** [comment] 2020-04-07 14:11
Cool, thanks a lot!

**Comment by mitchfriedman** [comment] 2020-04-21 11:51
fixed in https://github.com/garden-io/garden/pull/1805, can close this out

**Closed** 2020-05-04 11:34 UTC
Labels: bug, priority:high
