### ISSUE TITLE
[FEATURE]: Glob support for manifest paths in kubernetes actions

### ISSUE THREAD

**Issue by thelongshanx** [garden-io/garden#3138] opened 2022-08-24 21:21 UTC
## Feature Request

Regex support for paths

### Background / Motivation

If all of your manifests are in one directory, I want to be able to say “all of them” or “all the yaml files”. Garden doesn’t support directories or wildcards for specifying [files](https://docs.garden.io/reference/module-types/kubernetes#files) to be included in Kubernetes modules, which means you’ve got to list every file in the directory specifically.

### What should the user be able to do?

The user should be able to use wildcards or directory paths to specify a group of files.

### Why do they want to do this? What problem does it solve?

It saves a *whole* bunch of typing and upkeep. 

### Suggested Implementation(s)

Instead of listing every manifest in a directory like this:
```kind: Module
type: kubernetes
name: manifests
files:
- manifests/deploy.yml
- manifests/ingress.yml
- manifests/frontend.yml
- manifests/backend.yml```
…To being able to use REGEX point to directories like this:
```[...]
files:
- manifests/*.yml```
…Or at least having Garden be able to interpret a path to a directory as meaning “all the files in here” like this:
```[...]
files:
- manifests/```


### How important is this feature for you/your team?

🌹 It’s a nice to have, but nice things are nice 🙂

**Comment by vvagaytsev** [comment] 2023-07-11 11:04
Closing as a duplicate of #3465.

**Closed by vvagaytsev** 2023-07-11 11:04 UTC
Labels: feature request
