### ISSUE TITLE
Opening the dashboard before deployment is completed throws error in the console

### ISSUE THREAD

**Issue by raul-madrigal** [garden-io/garden#1148] opened 2019-09-03 15:17 UTC
### Current Behavior

<img width="1627" alt="Screen Shot 2019-09-03 at 9 14 36 AM" src="https://user-images.githubusercontent.com/30184031/64186006-58308080-ce2b-11e9-9075-4042de893ebf.png">

### Expected behavior

To open the dashboard without throwing errors in the console. It makes no sense to output the localhost URL to access the dashboard while is building if it's gonna throw errors.

### Your environment

`garden version: 0.10.6`

`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

`docker version: 19.03.1`

**Comment by edvald** [comment] 2019-09-03 16:28
Hmm hadn't seen this before, opening the dashboard before first deploy used to work fine. We'll take a look.

**Comment by eysi09** [comment] 2019-09-04 20:21
@raul-madrigal, does this only happen when you open the dashboard _before_ deployment is complete? It does indeed looks like the dashboard is making an API call that causes the error but I'm not sure why the timing would make a difference.

For what it's worth, opening the dashboard before deployment in the example projects works fine.

**Comment by raul-madrigal** [comment] 2019-09-04 21:02
Yes for sure, I confirm that it works after the deployment is completed. I opened the issue because if we know that the dashboard is not ready to present the data because the deployment is still in progress, then the console output shouldn't give the URL to access the dashboard, so we can avoid the error in the console, and only being able to open the dashboard until the deployment is ready.

**Comment by eysi09** [comment] 2019-09-27 15:18
I haven't seen this in any of our own projects and I suspect it is related to #1196. So I'm closing until we can reproduce.

**Closed by eysi09** 2019-09-27 15:18 UTC
Labels: bug, priority:medium
