### ISSUE TITLE
Error cleaning up cluster registry

### ISSUE THREAD

**Issue by Chipcius** [garden-io/garden#2274] opened 2021-02-25 13:48 UTC
## Bug
Failed cleaning images from in-cluster registry: Error: Could not find running pod for Deployment/garden-docker-registry

### Current Behavior

When I run `garden garden plugins kubernetes cleanup-cluster-registry` 

It looks like it is re-creating the docker-registry pod and goes into a failed state after being required to wait for the old container to die before getting access to the volume (previously attached to the old one)

### Expected behavior

The cleanup should happen without an error

### Reproducible example

Not sure if this is reproducible or not at the time or reporting. This might be a critical mass type issue as we have a lot of images in there ...
```
$ garden plugins kubernetes cleanup-cluster-registry
```

### Workaround

None known at the time of reporting this

### Additional context

```
$ garden plugins kubernetes cleanup-cluster-registry
Plugins 

Cleaning up caches and unused images from the in-cluster registry 

ℹ providers                 → Getting status...
✔ providers                 → Getting status... → Cached
   ℹ Run with --force-refresh to force a refresh of provider statuses.

ℹ Scanning all Pods in the cluster...
   Found 54 images in use in cluster, 30 referencing the in-cluster registry.
✔ Scanning all Pods in the cluster...
ℹ Listing all images in cluster registry...
   Found 30 images in the registry.
✔ Listing all images in cluster registry...
ℹ Flagging 0 unused images as deleted in cluster registry...
   Flagged 0 images as deleted in the registry.
✔ Flagging 0 unused images as deleted in cluster registry...
ℹ Running garbage collection in cluster registry...
   Fetching original Deployment
   Re-starting in read-only mode...
   ℹ docker-registry           → Waiting for resources to be ready...
   ℹ docker-registry           → Resources ready
   Running garbage collection...
   Restarting without read-only mode...
   ℹ docker-registry           → Waiting for resources to be ready...
   ⚠ docker-registry           → Deployment/garden-docker-registry: Multi-Attach error for volume "pvc-d0f8d2df-0535-4171-aeb2-d6bfe9fb19dc" Volume is already used by pod(s) garden-docker-registry-7f46867994-fj9qv
   ⚠ docker-registry           → Deployment/garden-docker-registry: AttachVolume.Attach succeeded for volume "pvc-d0f8d2df-0535-4171-aeb2-d6bfe9fb19dc" 
   ⚠ docker-registry           → Deployment/garden-docker-registry: Started container docker-registry
   ℹ docker-registry           → Resources ready
Failed cleaning images from in-cluster registry: Error: Could not find running pod for Deployment/garden-docker-registry

See error.log for details
```

```
$ cat error.log 

[2021-02-25T13:37:31.255Z] Could not find running pod for Deployment/garden-docker-registry

Error Details:

workload:
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: '1'
      kubectl.kubernetes.io/last-applied-configuration: >
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1","garden.io/manifest-hash":"b5a476f6d1abc102e5c6c91759f513189958614fbb332f1e3e9c53fe71d76f30","meta.helm.sh/release-name":"garden-docker-registry","meta.helm.sh/release-namespace":"garden-system"},"creationTimestamp":"2021-02-23T11:39:31.000Z","generation":2,"labels":{"app":"docker-registry","app.kubernetes.io/managed-by":"Helm","chart":"docker-registry-1.9.2","heritage":"Helm","release":"garden-docker-registry"},"name":"garden-docker-registry","namespace":"garden-system","resourceVersion":"10474242","selfLink":"/apis/apps/v1/namespaces/garden-system/deployments/garden-docker-registry","uid":"1d8b608c-d7f8-40a1-b3b9-4df33468fbf4"},"spec":{"minReadySeconds":5,"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"docker-registry","release":"garden-docker-registry"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"checksum/config":"21c689ec3d81d45fcfcddae6613f643f79613bc2eca72e396a6628930af6de54"},"creationTimestamp":null,"labels":{"app":"docker-registry","release":"garden-docker-registry"}},"spec":{"containers":[{"command":["/bin/registry","serve","/etc/docker/registry/config.yml"],"env":[{"name":"REGISTRY_HTTP_SECRET","valueFrom":{"secretKeyRef":{"key":"haSharedSecret","name":"garden-docker-registry-secret"}}},{"name":"REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY","value":"/var/lib/registry"},{"name":"REGISTRY_STORAGE_DELETE_ENABLED","value":"true"}],"image":"registry:2.7.1","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/","port":5000,"scheme":"HTTP"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"docker-registry","ports":[{"containerPort":5000,"protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/","port":5000,"scheme":"HTTP"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{"cpu":"2","memory":"4Gi"},"requests":{"cpu":"200m","memory":"512Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/lib/registry/","name":"data"},{"mountPath":"/etc/docker/registry","name":"garden-docker-registry-config"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"fsGroup":1000,"runAsUser":1000},"terminationGracePeriodSeconds":30,"tolerations":[{"effect":"NoSchedule","key":"garden-system","operator":"Equal","value":"true"}],"volumes":[{"name":"data","persistentVolumeClaim":{"claimName":"garden-docker-registry"}},{"configMap":{"defaultMode":420,"name":"garden-docker-registry-config"},"name":"garden-docker-registry-config"}]}}}}
      meta.helm.sh/release-name: garden-docker-registry
      meta.helm.sh/release-namespace: garden-system
      garden.io/manifest-hash: 1a516b21e90a3801f5b65b77c037209f422e8e74d7f59ff654f79b66c5e59cad
    creationTimestamp: '2021-02-23T11:39:31.000Z'
    generation: 3
    labels:
      app: docker-registry
      app.kubernetes.io/managed-by: Helm
      chart: docker-registry-1.9.2
      heritage: Helm
      release: garden-docker-registry
    name: garden-docker-registry
    namespace: garden-system
    resourceVersion: '10474755'
    selfLink: /apis/apps/v1/namespaces/garden-system/deployments/garden-docker-registry
    uid: 1d8b608c-d7f8-40a1-b3b9-4df33468fbf4
  spec:
    minReadySeconds: 5
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: docker-registry
        release: garden-docker-registry
    strategy:
      type: Recreate
    template:
      metadata:
```

Provider info
```
  - name: kubernetes
    buildMode: cluster-buildkit
    setupIngressController: nginx
    context: garden-dev
    storage:
      registry:
        size: 1000000
      sync:
        size: 1000000
    resources:
      builder:
        limits:
          memory: 5500
        requests:
          memory: 500
```

Registry disk usage report
```
 df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                 200.0G      4.6G    195.4G   2% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     3.7G         0      3.7G   0% /sys/fs/cgroup
/dev/nvme0n1p1          200.0G      4.6G    195.4G   2% /dev/termination-log
shm                      64.0M         0     64.0M   0% /dev/shm
/dev/nvme0n1p1          200.0G      4.6G    195.4G   2% /etc/resolv.conf
/dev/nvme0n1p1          200.0G      4.6G    195.4G   2% /etc/hostname
/dev/nvme0n1p1          200.0G      4.6G    195.4G   2% /etc/hosts
/dev/nvme0n1p1          200.0G      4.6G    195.4G   2% /etc/docker/registry
/dev/nvme1n1            961.5G    119.5G    842.0G  12% /var/lib/registry
tmpfs                     3.7G     12.0K      3.7G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                     3.7G         0      3.7G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/latency_stats
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                     3.7G         0      3.7G   0% /sys/firmware
```

### Your environment

* **OS:** Ubuntu 20.04
* **How I'm running Kubernetes:** EKS
* **Garden version:** 0.12.17

**Comment by eysi09** [comment] 2021-04-14 22:27
This is also a duplicate of #2172 which I just closed in favour of this one.

**Comment by eysi09** [comment] 2021-04-14 22:30
For anyone bumping into this, one workaround is to simply use an [external deployment registry](https://docs.garden.io/guides/in-cluster-building#configuring-a-deployment-registry). 

It scales better, does away with the need to operate the in-cluster registry and allows you to share caches across clusters.

**Comment by thsig** [comment] 2022-05-31 09:54
Closing this for now, since we're no longer recommending that people use the in-cluster registry once they're fully up and running with remote building on a daily basis.

Note that we've also deprecated the `cluster-docker` build mode since this issue was opened.

**Closed by thsig** 2022-05-31 09:54 UTC
Labels: bug
