### ISSUE TITLE
info-level CLI log lines are invisible when using the 'solarized-dark' terminal color theme

### ISSUE THREAD

**Issue by spenczar** [garden-io/garden#3538] opened 2023-01-17 19:08 UTC
### Current Behavior
Some of the colorized output (I think info-level?) is invisible in my terminal:
<img width="874" alt="Screen Shot 2023-01-17 at 10 36 49 AM" src="https://user-images.githubusercontent.com/880413/212986570-6111a623-83e4-4e8e-af66-01f0210bfa6e.png">

### Expected behavior

I expect to see all text output.

### Reproducible example

Use the "solarized-dark" theme (https://ethanschoonover.com/solarized/) in a terminal and run `garden get status`.

### Workaround

I can get around this using `FORCE_COLOR=0`.
I can also get around this by forking the solarized color theme and using my own with a custom color for "bright black."

### Suggested solution(s)

Use `chalk.dim` instead of `chalk.gray` in logging.

### Additional context

Ultimately, this is because Solarized doesn't really render "gray" (which is actually an alias for "bright black," it turns out) in a way that chalk expects. See https://github.com/chalk/chalk/issues/40. 

Solarized is a pretty popular color scheme. I realize this is ultimately my own fault for using this theme, but I figured I'd make a bug to raise the issue anyway, since the chalk developers suggest Using `chalk.dim` instead of `chalk.gray` to avoid this problem. 

### Your environment

* **OS:** Darwin MacBook-Pro.localdomain 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 arm64
* **How I'm running Kubernetes:** n/a

-> % garden version
0.12.48

**Comment by vvagaytsev** [comment] 2023-07-11 12:17
Closing as a duplicate of #2420

**Closed by vvagaytsev** 2023-07-11 12:17 UTC
Labels: bug, devex, triage/accepted
