### ISSUE TITLE
Manually running tests in interactive mode does not generate test artifacts

### ISSUE THREAD

**Issue by stumpc** [garden-io/garden#1475] opened 2020-01-03 21:03 UTC
### Current Behavior

When running garden tests in interactive mode (the default when using `garden run test`), the artifacts do not generate.  Running tests with the interactive flag set to false (`--interactive=false`) allows the artifacts to generate.

### Expected behavior

Artifacts should generate as defined whether or not `garden run test` is run with `--interactive=false` or `--interactive=true`

### Reproducible example

Run defined garden tests manually using `garden run test <module> <test-name>`.  Check your defined area in `.garden/artifacts` to find that no artifacts were generated.

Run defined garden tests manually using `garden run test <module> <test-name> --interactive=false`.  Check your defined area in `.garden/artifacts` to find that the artifacts were generated this time.

### Workaround

When manually running tests, use `--interactive=false`.

### Suggested solution(s)

I personally think that artifacts should generate regardless of the `--interactive` flag status.

### Your environment

`garden version`
0.10.16

`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
`docker version`
Docker version 19.03.5, build 633a0ea

**Comment by eysi09** [comment] 2020-06-08 15:00
Closing as a duplicate of #1739

**Closed by eysi09** 2020-06-08 15:00 UTC
Labels: bug, priority:medium
