### ISSUE TITLE
Kubernetes modules fail when manifest kind is List

### ISSUE THREAD

**Issue by padamson-r7** [garden-io/garden#2011] opened 2020-08-20 11:16 UTC
### Current Behavior

deploying a kubernetes module that uses List kind will throws this error:
```
Failed getting status for service 'spring-config-watcher' (from module 'spring-config-watcher'). Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Cannot read property 'namespace' of undefined
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

### Reproducible example

```
kind: Project
name: temp
environments:
- name: local
  providers:
  - name: local-kubernetes
    setupIngressController: false

---
  kind: Module
  type: kubernetes
  name: spring-config-watcher
  files: [spring-config-watcher.yml]
```

 where the manifest is of kind List:

```
---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
...
```
The full manifest I was using is here:
https://docs.spring.io/spring-cloud-kubernetes/docs/2.0.0-M3/reference/html/#deployment-yaml

### Workaround

refactor the List into a multi-document yaml file

(garden 0.12.2)

**Comment by vvagaytsev** [comment] 2023-07-04 11:19
This was fixed in #4501. Closing as a duplicate of #4500.

**Closed by vvagaytsev** 2023-07-04 11:19 UTC
Labels: bug, good first issue
