### ISSUE TITLE
0.13: [Bug]: Don't throw error but display easily understandable error message on wrongly configured action dependencies

### ISSUE THREAD

**Issue by twelvemo** [garden-io/garden#4738] opened 2023-07-03 16:12 UTC
### Current Behavior

If a dependency is set wrongly in a garden action, garden logs the error message and then crashes.

### Expected behavior

A configuration error like setting a dependency to the wrong action should not prompt an exception, but should be handled gracefully with a helpful error message.

### Reproducible example

Deploy the [garden quickstart example](https://github.com/garden-io/quickstart-example) and change the [dependencies for the vote service](https://github.com/garden-io/quickstart-example/blob/main/vote/garden.yml#L35) to reflect a wrong dependency e.g.:

```
 dependencies:
-  - deploy.api
+  - deploy.api-build
   - deploy.result
```

Run `garden deploy`. The output looks like this:

```
garden deploy
Deploy

Garden v0.13 (Bonsai) is a major release with significant changes. Please help us improve it by reporting any issues/bugs here:
https://go.garden.io/report-bonsai
→ Run garden util hide-warning 0.13-bonsai to disable this warning.
ℹ garden               → Running in Garden environment local.vote-demo-quickstart-anna
ℹ providers            → Getting status...
✔ providers            → Done (took 1.6 sec)
ℹ graph                → Resolving actions and modules...
✔ graph                → Done (took 0.6 sec)
✖ deploy.vote          → An internal error occurred while resolving status for resolve Deploy type=container name=vote. Here is the output:

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Could not find Deploy action api-build.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✖ deploy.e2e-runner    → An internal error occurred while resolving status for resolve Deploy type=container name=e2e-runner. Here is the output:

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Could not find Deploy action api-build.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✖ deploy.vote          → An internal error occurred while resolving status for resolve Deploy type=container name=vote. Here is the output:

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Could not find Deploy action api-build.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✖ deploy.e2e-runner    → An internal error occurred while resolving status for resolve Deploy type=container name=e2e-runner. Here is the output:

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Could not find Deploy action api-build.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✖ deploy.vote          → An internal error occurred while resolving status for resolve Deploy type=container name=vote. Here is the output:

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Could not find Deploy action api-build.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✖ deploy.e2e-runner    → An internal error occurred while resolving status for resolve Deploy type=container name=e2e-runner. Here is the output:

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Could not find Deploy action api-build.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
/snapshot/project/tmp/pkg/cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

GraphError: Could not find Deploy action api-build.
    at MutableConfigGraph.getActionByKind (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/graph/config-graph.ts:183:13)
    at MutableConfigGraph.getActionByRef (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/graph/config-graph.ts:172:30)
    at /snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/actions/base.ts:515:33
    at Array.forEach (<anonymous>)
    at DeployAction.getFullVersion (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/actions/base.ts:514:23)
    at DeployAction.<anonymous> (/snapshot/project/tmp/pkg/cli/node_modules/typescript-memoize/src/memoize-decorator.ts:123:36)
    at DeployAction.versionString (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/actions/base.ts:572:17)
    at wrapped.getInputVersion (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/tasks/base.ts:251:24)
    at wrapped.complete (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/graph/nodes.ts:122:31)
    at wrapped (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/util/profiling.ts:154:39)
    at /snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/graph/solver.ts:346:18 {
  detail: {
    available: {
      Build: [ 'result', 'worker', 'api-build', 'vote', 'e2e-runner' ],
      Deploy: [
        'api',
        'result',
        'vote',
        'worker',
        'postgres',
        'redis',
        'e2e-runner'
      ],
      Run: [ 'db-init', 'db-clear' ],
      Test: [ 'unit', 'e2e', 'unit-vote', 'e2e-vote' ]
    }
  },
  wrappedErrors: undefined,
  type: 'graph'
}

Node.js v18.1.0
```
The correct error message `Could not find deploy.api-build` is part of the long stack trace, but not clearly visible.

### Suggested solution(s)

Output the reason for the failing dependency and don't throw a `GraphError`.

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:**  K3s
`garden version`
0.13.5

**Comment by Walther** [comment] 2023-07-31 11:24
We looked into this with @shumailxyz and @vvagaytsev, and unfortunately there are no quick wins to be had here.

The errors are originating from here https://github.com/garden-io/garden/blob/86bb66f394c997bdd3c116414152c0c07e901af3/core/src/graph/config-graph.ts#L175-L189

One part of the problem is that in order to stop the execution, we do need to throw an error here. Another part of the problem is that we resolve the various actions in the graph concurrently, so the erroring code path will be triggered in _each_ action. (This can be confirmed by changing the code here to do simple `console.log`s and throw a new string error instead of the `GraphError` - you will see a lot of output.)

In theory, we could e.g. customize the `GraphError` to suppress a stacktrace, or add additinoal handling (try-catches on a higher level and adding special cases, and then exiting in a different location), but this could potentially add complexity and fragility to the system.

**Comment by Walther** [comment] 2023-08-01 09:13
Closing as not planned.

**Closed by Walther** 2023-08-01 09:13 UTC
Labels: devex, 0.13
