### ISSUE TITLE
[FEATURE]: Improve error messages when Kubernetes pod fails

### ISSUE THREAD

**Issue by 10ko** [garden-io/garden#3330] opened 2022-10-31 16:39 UTC
### Background / Motivation

As reported by some of our users, whenever a pod running a task or a test fail because of a Kubernetes error, Garden will only report the error code, which can be confusing or disorienting.

For example, in the case of an OOM error that instructs Kubernetes to evict the pod, Garden will only print: "received 129 error from pod".

### What should the user be able to do?

In case of an error that happens on the Kubernetes side (or any provider really), the user should receive actionable, useful information describing the cause of the issue and a potential solution.

### Why do they want to do this? What problem does it solve?
Getting suggestions from Garden itself on how to solve an issue instead of receiving a generic error message, makes debugging and resolving the issue easier.

### Suggested Implementation(s)

We could create a mapping between K8s errors and suggest solutions. E.g. in the case of 129, we could suggest how to configure the pods with increased resources. 
Additionally, we could print out the PodStatus and the lifecycles messages.

On a more general note, we could have a generic `PluginErrorHandler` that could be extended based on the error codes received when executing operations.

### How important is this feature for you/your team?

🌵 Not having this feature makes using Garden painful

**Comment by eysi09** [comment] 2022-11-06 16:15
@10ko, looks a duplicate of #3254, right? 

If you agree, would you mind closing and moving the conversation there?

**Comment by vvagaytsev** [comment] 2022-11-10 10:46
This relates to #3297.

**Closed** 2022-12-07 11:02 UTC
Labels: feature request, triage/accepted

**Comment by vvagaytsev** [comment] 2022-12-07 11:07
Partially fixed it #3388. Now the error messages are more informative, and failed pod status is printed if available.

Feel free to reopen it, if there are still some issues with non-informative errors on any non-zero error codes.

> We could create a mapping between K8s errors and suggest solutions. E.g. in the case of 129, we could suggest how to configure the pods with increased resources.
Additionally, we could print out the PodStatus and the lifecycles messages.
> 
> On a more general note, we could have a generic PluginErrorHandler that could be extended based on the error codes received when executing operations.
This part will be done in #3254.
