### ISSUE TITLE
maven-container not working with kaniko

### ISSUE THREAD

**Issue by alemairebe** [garden-io/garden#1983] opened 2020-08-07 13:34 UTC
### Current Behavior

When trying to build a maven-container module, it fails with 
*Unable to run docker command: Cannot read property 'spawnAndWait' of undefined* as my kubernetes provider is defined with *buildMode: kaniko*

### Expected behavior

maven-container should be able to produce a build and run with kaniko.

### Your environment

`garden version`

`kubectl version`

`docker version`

**Comment by eysi09** [comment] 2020-08-11 03:53
Hi @alemairebe 

Thanks for reporting this. Just to be sure, does it work otherwise with a normal container module? And does the maven container work otherwise for you if you're not using Kaniko?

**Comment by alemairebe** [comment] 2020-08-11 09:25
Hi @eysi09 

I have the same error message when trying to build with `buildMode: cluster-docker` with and without enableBuildKit ; same also with  `buildMode: local-docker`

garden version
0.12.2

docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Tue Jun 23 22:26:12 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Thu Jun 18 08:26:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:  

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by eysi09** [comment] 2020-08-13 15:45
Looks like this is a duplicate of #2002. I'll close this in favour of the newer one.

**Closed by eysi09** 2020-08-13 15:45 UTC
