### ISSUE TITLE
Feature request: Initialize Garden project using 'garden init'

### ISSUE THREAD

**Issue by Tails** [garden-io/garden#1305] opened 2019-11-02 19:47 UTC
I expected the ```garden init``` command to setup the garden project for me, perhaps using an interactive dialogue. Similar to ```git init``` and some other tools. Instead it seems there is no command to initialize a garden repository and one is supposed to write the YAML themselves.

**Comment by eysi09** [comment] 2019-11-03 23:54
Hi @Tails and thanks for the feedback.

We had a command that did just that but was pretty limited and ended up not being very useable. We therefore removed it but we're working on a proper re-implementation.

That command will be called `garden create project|module` as opposed to `garden init` which we already use for initialising system components.

I'll close this as duplicate of #312 which contains a bit more context (the original issue is pretty old but the we've bumped the feature on our roadmap).

**Closed by eysi09** 2019-11-03 23:54 UTC
