### ISSUE TITLE
[FEATURE]: using a specific version of Terraform identified by its path

### ISSUE THREAD

**Issue by johnlane** [garden-io/garden#3502] opened 2023-01-11 13:51 UTC
### Background / Motivation
Run Garden using a specific version of Terraform identified by its path

### What should the user be able to do?
Specify terraform version as a path to the executable (as opposed to `null` for the version on the path)

```
providers:
    - name: terraform
    - version: /path/to/terraform
```

### Why do they want to do this? What problem does it solve?
When project config assumes a TF version that is neither built into Garden nor on the path, this allows that terraform to be used by specifying its absolute path.

Currently unable to run garden when garden doesn't include the required TF version and the required TF version is not the one on the path.

This came about because

* garden update changed internal TF version to 1.2.9
* project config required prior internal TF version 0.13.3 
* project config did not configure `provider.version` for terraform in garden config (so the default changed from 0.13.3 to 1.2.9)
* already have TF executable for 0.13.3 but it is not the version on the path (that is 1.3.4).
* could not specify path to TF executable 0.13.3

I was able to have Garden download another copy of 0.13.3 by specifying `provider.version` and, ultimately, I ended up using the internal 1.2.9 version for current task but the inability to use a specific version remains an issue where the garden provided terraform verisons do not include the required version.

### How important is this feature for you/your team?
<strike> :cactus: Not having this feature makes using Garden painful </strike>
:rose: It’s a nice to have, but nice things are nice

**Comment by stefreak** [comment] 2023-01-12 11:38
@johnlane Thank you for taking the time to open this feature request!

I agree that it is suboptimal right now that it's not possible to choose any arbitrary Terraform version in `provider.version`.

Would it also be a solution for you if it was possible to provide any `provider.version` that is an official Hashicorp Terraform release instead of the current approach where we make only certain versions available to the Terraform provider?

**Comment by johnlane** [comment] 2023-01-13 17:36
Yes I think so, as long as you can get the version you want I guess it's fine.

**Comment by twelvemo** [comment] 2023-05-11 11:33
I think we should address this one after the bonsai release.

**Comment by stefreak** [comment] 2023-05-24 09:52
Closing this as duplicate of #4429

**Closed by stefreak** 2023-05-24 09:52 UTC
Labels: feature request, provider/terraform, reexamine-post-0.13, triage/accepted
